name: Create IAM account, change roles, delete IAM account

on: 
  
  workflow_dispatch:
    inputs:
 
#  push:
#    # Protection to avoid triggering when other workflow is modified
#    paths: 
#    - '!.github/workflows/**'
#    - '.github/workflows/gcloud-iam.yml'
    
#  schedule:
#    - cron:  '0 3 * * MON' 

env:
  GCP_VERBOSITY: warning
  GCP_SA: demoenv-serviceaccount@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com

jobs:
  create-serviceaccount-and-permissions-IAM:
  
    runs-on: ubuntu-latest 

    steps:
        
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        
    - name: Get gcloud version & info
      run: |-
        echo '--- gcloud version ---'
        gcloud version
        echo '--- gcloud info ---'
        gcloud info --anonymize
        
    - name: Create service account
      run: |-
        gcloud iam service-accounts create service-demoenv-account \
        --description="Dynamic service account from demoenv. It should not exists for more than five minutes" \
        --display-name="service-demoenv-account"